# Generated by Django 5.1.7 on 2025-03-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imgUrl',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
