# Generated by Django 5.1.7 on 2025-03-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_imgurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imgUrl',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
